# Summary
\setstretch{1.2}
In various species, sex determination is associated with an imbalance in the number of sex chromosomes between males and females. In *Drosophila*, this imbalance is corrected by an chromosome-level epigenetic phenomenon resulting in the upregulation of gene expression on the single male X chromosome. This phenomenon, referred to as dosage compensation, requires the Male-specific lethal (MSL) complex. The 3D conformation of the X-chromosome guides the spreading of the MSL complex, depositing histone (H4K16) acetylation on genes. On the other hand, mammalian dosage compensation occurs via X inactivation in females, and the role of MSL complex in mammals is poorly understood.

The aim of my project was to provide insights into the functions of the MSL complex in flies and mammals through computational epigenomics approach. This involved development of methods and tools for analysis of chromosome conformation and promoter-profiling data, and their integration with other transcriptomic and epigenetic data. Software such as HiCExplorer, icetea and deepTools2 were developed to facilitate this, and workflows for reproducible analysis were implemented as part of the snakePipes package. Application of our methods on HiC data in flies revealed that chromatin domains influence gene transcription, and validated previous observation on clustering of MSL2 sites in 3D space. Analysis of the MSL complex member MLE through promoter profiling identified a catalogue of MLE sensitive and insensitive promoters at the male X-chromosome and the difference in MLE action between sexes. Analysis of mammalian ortholog of MLE revealed it’s novel function in the regulation of Alu transposons independent of the MSL complex, while the analysis of other members of the mammalian MSL complex showed that MSLs are involved in transcriptional regulation of genes on X chromosome in an allele-specific manner.

In summary, we gained new insights into the functions of the MSL complex through analysis and integration of multiple epigenomic and transcriptomic data. This study would motivate further studies utilizing integrative epigenomics to understand the functions of MSLs as well as other regulators of transcription.
\setstretch{1.5}